lubelogger:
  
  replicaCount: 2

  nodeSelector:
    class: sanji
  
  config:
    # `Warning`, `Error`, `Critical` and `None`. Learn more at:
    # https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/
    LOGLEVEL: Debug
  
    userConfig:
      Logging:
        LogLevel:
          Default: Debug
          Microsoft.AspNetCore: Warning
      UseDarkMode: true
      EnableAuth: false
      UseMarkDownOnSavedNotes: true

  secret:
    create: false
    name: "lubelogger-creds"

  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000

  service:
    type: NodePort

  persistence:
    data:
      enabled: true
      existingClaim: lubelogger-data
  
  postgres:
    create: false
    connect: true
  
