apiVersion: v2
name: planka
description: Planka, the Trello clone.

type: application
version: 1.1.1

dependencies:
  - name: planka
    version: 1.1.1
    repository: https://plankanban.github.io/planka

