apiVersion: v2
name: planka
description: Planka, the Trello clone.

type: application
version: 1.2.0

dependencies:
  - name: planka
    version: 2.0.2
    repository: https://plankanban.github.io/planka

