planka:
  replicaCount: 2
  
  existingSecretkeySecret: "planka-secretkey"
  existingAdminCredsSecret: "planka-admin-creds"
  baseUrl: "https://planka.magdavis.click"

  nodeSelector:
    class: sanji

  persistence:
    enabled: true
    existingClaim: planka
    accessMode: ReadWriteMany
    size: 5Gi

  postgresql:
    enabled: false

  securityContext:
    runAsUser: 1000
    runAsGroup: 1000

  service:
    type: NodePort

  existingDburlSecret: "planka-dburl"

