planka:
  replicaCount: 2
  
  existingSecretkeySecret: "planka-secretkey"
  existingAdminCredsSecret: "planka-admin-creds"
  baseUrl: "https://planka.magdavis.click"

  nodeSelector:
    class: sanji

  postgresql:
    enabled: false

  service:
    type: NodePort
    port: 13370

  existingDburlSecret: "planka-dburl"

