apiVersion: v2
name: argocd-image-updater
description: ArgoCD Image Updater

version: 1.0.1

home: https://github.com/argoproj/argo-helm
icon: https://raw.githubusercontent.com/argoproj/argo/master/docs/assets/argo.png

dependencies:
  - name: argocd-image-updater
    version: 1.1.0
    repository: https://argoproj.github.io/argo-helm

