apiVersion: v2
name: nextcloud
description: Nextcloud
icon: https://cdn.rawgit.com/docker-library/docs/defa5ffc7123177acd60ddef6e16bddf694cc35f/nextcloud/logo.svg

type: application
version: 1.2.3

dependencies:
  - name: nextcloud
    version: 8.9.1
    repository: "https://nextcloud.github.io/helm/"

